"""
Django settings for oa2client project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u7q$v!5f7n1h+hl(%t-2n5^8%6ldg9ek0d-be8t$2z1@5(nrhk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oa2client.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'oa2client', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oa2client.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'oa2client',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# Auth

LOGIN_URL = '/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

# social-auth-app-django
# https://github.com/python-social-auth/social-app-django


AUTHENTICATION_BACKENDS = (
    'oa2client.backends.ForAllBackpackOAuth2',
#   'social_core.backends.google.GoogleOpenId',
#   'social_core.backends.google.GoogleOAuth2',
#   'social_core.backends.google.GoogleOAuth',
#   'social_core.backends.twitter.TwitterOAuth',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_PIPELINE = (
    # Get the information we can about the user
    # - calls backend.get_user_details()
    'social_core.pipeline.social_auth.social_details',
    # Get the social uid (unique identifier of the given user in the provider)
    # - define backend.ID_KEY
    'social_core.pipeline.social_auth.social_uid',
    # Checks if the current social-account is already associated in the site.
    'social_core.pipeline.social_auth.social_user',
    # Make up a username for this person, appends a random string at the end if
    # there's any collision.
    'social_core.pipeline.user.get_username',
    # Create a user account if we haven't found one yet.
    'social_core.pipeline.user.create_user',
    # Create the record that associates the social account with the user.
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
)

SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    # Collects the social associations to disconnect
    'social_core.pipeline.disconnect.get_entries',
    # Revoke any access_token when possible
    'social_core.pipeline.disconnect.revoke_tokens',
)

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'

SOCIAL_AUTH_LOGIN_ERROR_URL = '/'

# The user will be redirected to this URL when a social account is disconnected
SOCIAL_AUTH_DISCONNECT_REDIRECT_URL = 'http://127.0.0.1:8000/logout/?next=http://0.0.0.0:5000/logout/'

SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True

# client_id, client_secret from FAB Application record
SOCIAL_AUTH_FORALLBACKPACK_KEY = 'a3j8aKJAINbj2eowzvpkRhBLvQqj9J9xVPQWjg7r'
SOCIAL_AUTH_FORALLBACKPACK_SECRET = 'j6UoAeM6KKHWMRDr55W7Omn6irYhIMiuwtPxbQ1mLLLp7Nvfyozyl01qtr66MzIRJxcxanaOGY1XAxuHsrrvNgw50hfQtY84cICK0B51LYGml9TRm84iQSlWysZdZGFj'

# oa2client.backends.ForAllBackpackOAuth2
FAB_SERVER_URL = 'http://127.0.0.1:8000'
FAB_CLIENT_ID  = 'kwpuwh6by4DZSbR5vW47sgUhBcKV93fIn2UNGD9a'
FAB_CLIENT_SECRET = '9MtmC2EiAK9MGLikjmnp7rKxbsAJz8xvrHrlWFQ4r1vlIqhKmiVP8BwRapIzsk8WSrR1e1zT5wu4TVbzPPkQKkGS3Vi1Y4XB0FI7eVppil9ndu0hakqsXcBzfhUSGces'





